#!/bin/sh

echo -e "\033[1mStart scanning ext2/4 block device\033[0m"

lsblk -o PATH,FSTYPE | while read path fstype
do
    if [ "$fstype" == "ext2" ] || [ "$fstype" == "ext4" ]
    then
        echo "Start zerofree on $path ($fstype) this can take a while ..."
        time zerofree $path
    fi
done

echo -e "\033[1mAll block device where freed. Now poweroff ...\033[0m"
poweroff
