#!/bin/sh

echo ""
echo -e "\\e[1mStart scanning ext2/4 block device\\e[0m"

lsblk -o PATH,FSTYPE | while read path fstype
do
    if [ "$fstype" == "ext2" ] || [ "$fstype" == "ext4" ]
    then
        echo -e "Start zerofree on \\e[1;34m$path\\e[0m ($fstype) this can take a while ..."
        zerofree -v $path
    fi
done

echo ""
echo -e "\\e[1mAll ext2/4 filesystem where shrinked. Now poweroff ...\\e[0m"
poweroff
